---
apiVersion: v1
kind: ConfigMap
metadata:
  name: parse-json
  namespace: kube-system
  labels:
    k8s-app: fluentd
    version: v1
    kubernetes.io/cluster-service: "true"
data:
  parse-json.conf: |-
    <filter kubernetes.**>
      @type parser
      format json
      key_name log
      reserve_data true
      ignore_key_not_exist true
      suppress_parse_error_log true
    </filter>
