---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  labels:
    app.kubernetes.io/name: {{ include "helm-fluentd-kinesis-firehose.name" . }}
    helm.sh/chart: {{ include "helm-fluentd-kinesis-firehose.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  fluent.conf: |-
    @include systemd.conf
    @include kubernetes.conf
    @include conf.d/*.conf
    <match **>
      @type kinesis_firehose
      @id out_kinesis_firehose
      region "#{ENV['FLUENT_KINESIS_STREAMS_REGION'] || nil}"
      delivery_stream_name "#{ENV['FLUENT_KINESIS_DELIVERY_STREAM_NAME']}"
      include_time_key "#{ENV['FLUENT_KINESIS_STREAMS_INCLUDE_TIME_KEY'] || false}"
      flush_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_INTERVAL'] || '1'}"
      buffer_chunk_limit "#{ENV['FLUENT_BUFFER_CHUNK_LIMIT_SIZE'] || '2M'}"
      buffer_queue_limit "#{ENV['FLUENT_BUFFER_QUEUE_LIMIT_LENGTH'] || '32'}"
      try_flush_interval "#{ENV['FLUENT_TRY_FLUSH_INTERVAL'] || '0.1'}"
      queued_chunk_flush_interval "#{ENV['FLUENT_QUEUED_CHUNK_FLUSH_INTERVAL'] || '0.01'}"
      num_threads "#{ENV['FLUENT_BUFFER_FLUSH_THREAD_COUNT'] || '15'}"
{{- if .Values.fluentEnvs.useRole }}
      <assume_role_credentials>
        role_arn "#{ENV['ROLE_ARN']}"
        role_session_name "#{ENV['ROLE_SESSION_NAME']}"
      </assume_role_credentials>
{{- end}}
    </match>
