---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-config
  labels:
    app.kubernetes.io/name: {{ include "helm-fluentd-kinesis-firehose.name" . }}
    helm.sh/chart: {{ include "helm-fluentd-kinesis-firehose.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  kubernetes.conf: |-
    <match fluent.**>
      @type null
    </match>

    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      format json
      time_format %Y-%m-%dT%H:%M:%S.%NZ
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
    </filter>
