---
apiVersion: v1
kind: ConfigMap
metadata:
  name: parse-json
  labels:
    app.kubernetes.io/name: {{ include "helm-fluentd-kinesis-firehose.name" . }}
    helm.sh/chart: {{ include "helm-fluentd-kinesis-firehose.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  parse-json.conf: |-
    <filter kubernetes.**>
      @type parser
      format json
      key_name log
      reserve_data true
      ignore_key_not_exist true
      suppress_parse_error_log true
    </filter>
