{{ if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "helm-fluentd-kinesis-firehose.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "helm-fluentd-kinesis-firehose.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "helm-fluentd-kinesis-firehose.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "helm-fluentd-kinesis-firehose.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}